site_name: CSP Project
site_url: https://ccf-csp-project.github.io/CSP-Project-with-MkDocs/
repo_url: https://github.com/ccf-csp-project/CSP-Project-with-MkDocs
repo_name: CSP Project with MkDocs
theme: 
  name: material
  language: zh
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking

nav:
  - 简介: 
    - index.md
    - 关于本项目: introduction/about.md
    - 如何参与: introduction/contributing.md
    - 如何编写自己的题解页面: introduction/write_passage.md
    - 常见问题解答: introduction/faq.md
  - 题目列表: 
    - problem/index.md
    - 第 24 次: 
      - problem/24/index.md
      - 202112-1 序列查询: 
        - problem/24/1/index.md
        - 文章 1: problem/24/1/1.md
      - 202112-2 序列查询新解: 
        - problem/24/2/index.md
        - 文章 1: problem/24/2/1.md
        - 文章 2: problem/24/2/2.md
      - 202112-3 登机牌号码: 
        - problem/24/3/index.md
        - 文章 1: problem/24/3/1.md
      - 202112-4 磁盘文件操作: 
        - problem/24/4/index.md
        - 文章 1: problem/24/4/1.md
    - 第 23 次:
      - problem/23/index.md
      - 202109-1 数组推导:
        - problem/23/1/index.md
        - 文章 1: problem/23/1/1.md
      - 202109-2 非零段划分:
        - problem/23/2/index.md
        - 文章 1: problem/23/2/1.md
      - 202109-3 脉冲神经网络:
        - problem/23/3/index.md
        - 文章 1: problem/23/3/1.md
      - 202109-4 收集卡牌:
        - problem/23/4/index.md
        - 文章 1: problem/23/4/1.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - def_list
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

