site_name: CSP Project
site_url: https://lxlonlyn.github.io/CSP-Project-with-MkDocs/
repo_url: https://github.com/lxlonlyn/CSP-Project-with-MkDocs
site_author: lonlyn
theme: material

nav:
    - 主页: index.md
    - 题目列表: 
      - 第 24 次: 
        - 总览: 24/main.md
        - 202112-1 序列查询: 24/1.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

